import { ethers } from 'ethers';
import { StellarWalletsKit, WalletType } from '@stellar/freighter-api';

class BlockchainService {
  constructor() {
    this.provider = null;
    this.signer = null;
    this.stellarKit = null;
    this.network = 'testnet'; // Change to 'mainnet' for production
  }

  // Ethereum Integration
  async connectEthereumWallet() {
    try {
      if (!window.ethereum) {
        throw new Error('MetaMask is not installed');
      }

      await window.ethereum.request({ method: 'eth_requestAccounts' });
      
      this.provider = new ethers.BrowserProvider(window.ethereum);
      this.signer = await this.provider.getSigner();
      
      const address = await this.signer.getAddress();
      const balance = await this.provider.getBalance(address);
      
      return {
        address,
        balance: ethers.formatEther(balance),
        chainId: (await this.provider.getNetwork()).chainId
      };
    } catch (error) {
      throw new Error(`Failed to connect Ethereum wallet: ${error.message}`);
    }
  }

  async mintEthereumNFT(contractAddress, tokenId, metadataURI) {
    try {
      if (!this.signer) {
        throw new Error('Wallet not connected');
      }

      // Simple ERC-721 mint function interface
      const contractABI = [
        "function mint(address to, uint256 tokenId, string tokenURI) external",
        "function ownerOf(uint256 tokenId) external view returns (address)"
      ];

      const contract = new ethers.Contract(contractAddress, contractABI, this.signer);
      
      const tx = await contract.mint(
        await this.signer.getAddress(),
        tokenId,
        metadataURI
      );

      const receipt = await tx.wait();
      
      return {
        transactionHash: receipt.hash,
        blockNumber: receipt.blockNumber,
        gasUsed: receipt.gasUsed.toString(),
        status: receipt.status === 1 ? 'success' : 'failed'
      };
    } catch (error) {
      throw new Error(`Ethereum minting failed: ${error.message}`);
    }
  }

  // Stellar Integration
  async connectStellarWallet() {
    try {
      this.stellarKit = new StellarWalletsKit({
        selectedWallet: WalletType.FREIGHTER,
        network: this.network
      });

      const { address, publicKey } = await this.stellarKit.getPublicKey();
      
      // Get account info
      const { horizon } = this.stellarKit;
      const account = await horizon.server.loadAccount(publicKey);
      
      return {
        address: publicKey,
        balance: account.balances,
        network: this.network
      };
    } catch (error) {
      throw new Error(`Failed to connect Stellar wallet: ${error.message}`);
    }
  }

  async mintStellarNFT(assetCode, assetIssuer, metadata) {
    try {
      if (!this.stellarKit) {
        throw new Error('Stellar wallet not connected');
      }

      // This is a simplified example - actual Stellar NFT minting would involve
      // creating a token contract or using an existing NFT protocol
      const transaction = await this.stellarKit.createAsset({
        code: assetCode,
        issuer: assetIssuer,
        metadata: metadata
      });

      const result = await this.stellarKit.signAndSubmitTransaction(transaction);
      
      return {
        transactionHash: result.hash,
        ledger: result.ledger,
        status: result.status === 'success' ? 'success' : 'failed'
      };
    } catch (error) {
      throw new Error(`Stellar minting failed: ${error.message}`);
    }
  }

  // Generic minting function that chooses blockchain based on user preference
  async mintArtwork(artwork, blockchain = 'ethereum', contractConfig = {}) {
    try {
      const metadata = {
        name: artwork.title,
        description: artwork.description,
        image: artwork.image,
        created: artwork.createdAt,
        attributes: [
          {
            trait_type: "Generated by",
            value: "AI"
          },
          {
            trait_type: "Status",
            value: artwork.status
          }
        ]
      };

      // Upload metadata to IPFS (mock implementation)
      const metadataURI = await this.uploadToIPFS(metadata);

      switch (blockchain) {
        case 'ethereum':
          return await this.mintEthereumNFT(
            contractConfig.contractAddress,
            artwork.id,
            metadataURI
          );
        
        case 'stellar':
          return await this.mintStellarNFT(
            contractConfig.assetCode || `ART${artwork.id}`,
            contractConfig.assetIssuer || await this.signer.getAddress(),
            metadataURI
          );
        
        default:
          throw new Error('Unsupported blockchain');
      }
    } catch (error) {
      throw new Error(`Minting failed: ${error.message}`);
    }
  }

  // IPFS Upload (mock implementation - replace with actual IPFS service)
  async uploadToIPFS(data) {
    try {
      // Mock IPFS upload - replace with actual IPFS client
      const mockCID = `bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi${Date.now()}`;
      return `ipfs://${mockCID}`;
    } catch (error) {
      throw new Error(`IPFS upload failed: ${error.message}`);
    }
  }

  // Get transaction status
  async getTransactionStatus(txHash, blockchain = 'ethereum') {
    try {
      switch (blockchain) {
        case 'ethereum':
          if (!this.provider) throw new Error('Ethereum provider not connected');
          const receipt = await this.provider.getTransactionReceipt(txHash);
          return {
            status: receipt.status === 1 ? 'success' : 'failed',
            blockNumber: receipt.blockNumber,
            gasUsed: receipt.gasUsed.toString()
          };
        
        case 'stellar':
          if (!this.stellarKit) throw new Error('Stellar wallet not connected');
          const { horizon } = this.stellarKit;
          const tx = await horizon.server.transactions().transaction(txHash).call();
          return {
            status: tx.successful ? 'success' : 'failed',
            ledger: tx.ledger,
            fee_paid: tx.fee_paid
          };
        
        default:
          throw new Error('Unsupported blockchain');
      }
    } catch (error) {
      throw new Error(`Failed to get transaction status: ${error.message}`);
    }
  }

  // Disconnect wallet
  disconnect() {
    this.provider = null;
    this.signer = null;
    this.stellarKit = null;
  }
}

export default BlockchainService;
